create materialized view data_models.player_shots as (
    select l.match_id,
       l.match_date,
       l.team,
       l.home,
       l.formation,
       l.starter,
       l.player_link,
       p.player,
       p.position,
       p.minutes,
       p.touches,
       p.goals,
       p.pens_made,
       p.pens_att,
       p.shots_total,
       p.shots_on_target,
       p.xg,
       p.npxg,
       p.xa,
       p.sca as shot_creating_action,
       p.gca as goal_creating_action,
       p.assisted_shots,
       p.touches_att_3rd,
       p.touches_att_pen_area,
       p.touches_live_ball,
       p.carries_into_penalty_area,
       p.carries_into_final_third,
       p.miscontrols,
       p.dispossessed,
       p.pass_targets,
       p.passes_received,
       p.progressive_passes_received,
       p.offsides,
       p.aerials_won,
       p.aerials_lost
    from raw.players p
        inner join raw.lineups l on p.player_link = l.player_link and p.match_id = l.match_id
);