INSERT INTO raw.players (
    match_id,
    match_date,
    season,
    player_link,
    player,
    shirtnumber,
    country_link,
    nationality,
    position,
    age,
    minutes,
    goals,
    assists,
    pens_made,
    pens_att,
    shots_total,
    shots_on_target,
    cards_yellow,
    cards_red,
    touches,
    pressures,
    tackles,
    interceptions,
    blocks,
    xg,
    npxg,
    xa,
    sca,
    gca,
    passes_completed,
    passes,
    passes_pct,
    progressive_passes,
    carries,
    progressive_carries,
    dribbles_completed,
    dribbles,
    passes_total_distance,
    passes_progressive_distance,
    passes_completed_short,
    passes_short,
    passes_pct_short,
    passes_completed_medium,
    passes_medium,
    passes_pct_medium,
    passes_completed_long,
    passes_long,
    passes_pct_long,
    assisted_shots,
    passes_into_final_third,
    passes_into_penalty_area,
    crosses_into_penalty_area,
    passes_live,
    passes_dead,
    passes_free_kicks,
    through_balls,
    passes_pressure,
    passes_switches,
    crosses,
    corner_kicks,
    corner_kicks_in,
    corner_kicks_out,
    corner_kicks_straight,
    passes_ground,
    passes_low,
    passes_high,
    passes_left_foot,
    passes_right_foot,
    passes_head,
    throw_ins,
    passes_other_body,
    passes_offsides,
    passes_oob,
    passes_intercepted,
    passes_blocked,
    tackles_won,
    tackles_def_3rd,
    tackles_mid_3rd,
    tackles_att_3rd,
    dribble_tackles,
    dribbles_vs,
    dribble_tackles_pct,
    dribbled_past,
    pressure_regains,
    pressure_regain_pct,
    pressures_def_3rd,
    pressures_mid_3rd,
    pressures_att_3rd,
    blocked_shots,
    blocked_shots_saves,
    blocked_passes,
    tackles_interceptions,
    clearances,
    errors,
    touches_def_pen_area,
    touches_def_3rd,
    touches_mid_3rd,
    touches_att_3rd,
    touches_att_pen_area,
    touches_live_ball,
    dribbles_completed_pct,
    players_dribbled_past,
    nutmegs,
    carry_distance,
    carry_progressive_distance,
    carries_into_final_third,
    carries_into_penalty_area,
    miscontrols,
    dispossessed,
    pass_targets,
    passes_received,
    passes_received_pct,
    progressive_passes_received,
    cards_yellow_red,
    fouls,
    fouled,
    offsides,
    pens_won,
    pens_conceded,
    own_goals,
    ball_recoveries,
    aerials_won,
    aerials_lost,
    aerials_won_pct
) SELECT * FROM temp.players
ON CONFLICT ON CONSTRAINT players_pk
DO UPDATE SET
    match_id = excluded.match_id,
    match_date = excluded.match_date,
    season = excluded.season,
    player_link = excluded.player_link,
    player = excluded.player,
    shirtnumber = excluded.shirtnumber,
    country_link = excluded.country_link,
    nationality = excluded.nationality,
    position = excluded.position,
    age = excluded.age,
    minutes = excluded.minutes,
    goals = excluded.goals,
    assists = excluded.assists,
    pens_made = excluded.pens_made,
    pens_att = excluded.pens_att,
    shots_total = excluded.shots_total,
    shots_on_target = excluded.shots_on_target,
    cards_yellow = excluded.cards_yellow,
    cards_red = excluded.cards_red,
    touches = excluded.touches,
    pressures = excluded.pressures,
    tackles = excluded.tackles,
    interceptions = excluded.interceptions,
    blocks = excluded.blocks,
    xg = excluded.xg,
    npxg = excluded.npxg,
    xa = excluded.xa,
    sca = excluded.sca,
    gca = excluded.gca,
    passes_completed = excluded.passes_completed,
    passes = excluded.passes,
    passes_pct = excluded.passes_pct,
    progressive_passes = excluded.progressive_passes,
    carries = excluded.carries,
    progressive_carries = excluded.progressive_carries,
    dribbles_completed = excluded.dribbles_completed,
    dribbles = excluded.dribbles,
    passes_total_distance = excluded.passes_total_distance,
    passes_progressive_distance = excluded.passes_progressive_distance,
    passes_completed_short = excluded.passes_completed_short,
    passes_short = excluded.passes_short,
    passes_pct_short = excluded.passes_pct_short,
    passes_completed_medium = excluded.passes_completed_medium,
    passes_medium = excluded.passes_medium,
    passes_pct_medium = excluded.passes_pct_medium,
    passes_completed_long = excluded.passes_completed_long,
    passes_long = excluded.passes_long,
    passes_pct_long = excluded.passes_pct_long,
    assisted_shots = excluded.assisted_shots,
    passes_into_final_third = excluded.passes_into_final_third,
    passes_into_penalty_area = excluded.passes_into_penalty_area,
    crosses_into_penalty_area = excluded.crosses_into_penalty_area,
    passes_live = excluded.passes_live,
    passes_dead = excluded.passes_dead,
    passes_free_kicks = excluded.passes_free_kicks,
    through_balls = excluded.through_balls,
    passes_pressure = excluded.passes_pressure,
    passes_switches = excluded.passes_switches,
    crosses = excluded.crosses,
    corner_kicks = excluded.corner_kicks,
    corner_kicks_in = excluded.corner_kicks_in,
    corner_kicks_out = excluded.corner_kicks_out,
    corner_kicks_straight = excluded.corner_kicks_straight,
    passes_ground = excluded.passes_ground,
    passes_low = excluded.passes_low,
    passes_high = excluded.passes_high,
    passes_left_foot = excluded.passes_left_foot,
    passes_right_foot = excluded.passes_right_foot,
    passes_head = excluded.passes_head,
    throw_ins = excluded.throw_ins,
    passes_other_body = excluded.passes_other_body,
    passes_offsides = excluded.passes_offsides,
    passes_oob = excluded.passes_oob,
    passes_intercepted = excluded.passes_intercepted,
    passes_blocked = excluded.passes_blocked,
    tackles_won = excluded.tackles_won,
    tackles_def_3rd = excluded.tackles_def_3rd,
    tackles_mid_3rd = excluded.tackles_mid_3rd,
    tackles_att_3rd = excluded.tackles_att_3rd,
    dribble_tackles = excluded.dribble_tackles,
    dribbles_vs = excluded.dribbles_vs,
    dribble_tackles_pct = excluded.dribble_tackles_pct,
    dribbled_past = excluded.dribbled_past,
    pressure_regains = excluded.pressure_regains,
    pressure_regain_pct = excluded.pressure_regain_pct,
    pressures_def_3rd = excluded.pressures_def_3rd,
    pressures_mid_3rd = excluded.pressures_mid_3rd,
    pressures_att_3rd = excluded.pressures_att_3rd,
    blocked_shots = excluded.blocked_shots,
    blocked_shots_saves = excluded.blocked_shots_saves,
    blocked_passes = excluded.blocked_passes,
    tackles_interceptions = excluded.tackles_interceptions,
    clearances = excluded.clearances,
    errors = excluded.errors,
    touches_def_pen_area = excluded.touches_def_pen_area,
    touches_def_3rd = excluded.touches_def_3rd,
    touches_mid_3rd = excluded.touches_mid_3rd,
    touches_att_3rd = excluded.touches_att_3rd,
    touches_att_pen_area = excluded.touches_att_pen_area,
    touches_live_ball = excluded.touches_live_ball,
    dribbles_completed_pct = excluded.dribbles_completed_pct,
    players_dribbled_past = excluded.players_dribbled_past,
    nutmegs = excluded.nutmegs,
    carry_distance = excluded.carry_distance,
    carry_progressive_distance = excluded.carry_progressive_distance,
    carries_into_final_third = excluded.carries_into_final_third,
    carries_into_penalty_area = excluded.carries_into_penalty_area,
    miscontrols = excluded.miscontrols,
    dispossessed = excluded.dispossessed,
    pass_targets = excluded.pass_targets,
    passes_received = excluded.passes_received,
    passes_received_pct = excluded.passes_received_pct,
    progressive_passes_received = excluded.progressive_passes_received,
    cards_yellow_red = excluded.cards_yellow_red,
    fouls = excluded.fouls,
    fouled = excluded.fouled,
    offsides = excluded.offsides,
    pens_won = excluded.pens_won,
    pens_conceded = excluded.pens_conceded,
    own_goals = excluded.own_goals,
    ball_recoveries = excluded.ball_recoveries,
    aerials_won = excluded.aerials_won,
    aerials_lost = excluded.aerials_lost,
    aerials_won_pct = excluded.aerials_won_pct;