INSERT INTO raw.goalkeepers (
    match_id,
    match_date,
    season,
    competition,
    player_link,
    player,
    country_link,
    nationality,
    age,
    minutes,
    gk_shots_on_target_against,
    gk_goals_against,
    gk_saves,
    gk_save_pct,
    gk_psxg,
    gk_passes_completed_launched,
    gk_passes_launched,
    gk_passes_pct_launched,
    gk_passes,
    gk_passes_throws,
    gk_pct_passes_launched,
    gk_passes_length_avg,
    gk_goal_kicks,
    gk_pct_goal_kicks_launched,
    gk_goal_kick_length_avg,
    gk_crosses,
    gk_crosses_stopped,
    gk_crosses_stopped_pct,
    gk_def_actions_outside_pen_area,
    gk_avg_distance_def_actions
) SELECT * FROM staging.goalkeepers
ON CONFLICT ON CONSTRAINT goalkeepers_pk
DO UPDATE SET
    match_id = excluded.match_id,
    match_date = excluded.match_date,
    season = excluded.season,
    competition = excluded.competition,
    player_link = excluded.player_link,
    player = excluded.player,
    country_link = excluded.country_link,
    nationality = excluded.nationality,
    age = excluded.age,
    minutes = excluded.minutes,
    gk_shots_on_target_against = excluded.gk_shots_on_target_against,
    gk_goals_against = excluded.gk_goals_against,
    gk_saves = excluded.gk_saves,
    gk_save_pct = excluded.gk_save_pct,
    gk_psxg = excluded.gk_psxg,
    gk_passes_completed_launched = excluded.gk_passes_completed_launched,
    gk_passes_launched = excluded.gk_passes_launched,
    gk_passes_pct_launched = excluded.gk_passes_pct_launched,
    gk_passes = excluded.gk_passes,
    gk_passes_throws = excluded.gk_passes_throws,
    gk_pct_passes_launched = excluded.gk_pct_passes_launched,
    gk_passes_length_avg = excluded.gk_passes_length_avg,
    gk_goal_kicks = excluded.gk_goal_kicks,
    gk_pct_goal_kicks_launched = excluded.gk_pct_goal_kicks_launched,
    gk_goal_kick_length_avg = excluded.gk_goal_kick_length_avg,
    gk_crosses = excluded.gk_crosses,
    gk_crosses_stopped = excluded.gk_crosses_stopped,
    gk_crosses_stopped_pct = excluded.gk_crosses_stopped_pct,
    gk_def_actions_outside_pen_area = excluded.gk_def_actions_outside_pen_area,
    gk_avg_distance_def_actions = excluded.gk_avg_distance_def_actions;