INSERT INTO raw.goalkeepers (
    match_id,
    match_date,
    season,
    player_link,
    player,
    country_link,
    nationality,
    age,
    minutes,
    shots_on_target_against,
    goals_against_gk,
    saves,
    save_pct,
    psxg_gk,
    passes_completed_launched_gk,
    passes_launched_gk,
    passes_pct_launched_gk,
    passes_gk,
    passes_throws_gk,
    pct_passes_launched_gk,
    passes_length_avg_gk,
    goal_kicks,
    pct_goal_kicks_launched,
    goal_kick_length_avg,
    crosses_gk,
    crosses_stopped_gk,
    crosses_stopped_pct_gk,
    def_actions_outside_pen_area_gk,
    avg_distance_def_actions_gk
) SELECT * FROM temp.goalkeepers
ON CONFLICT ON CONSTRAINT goalkeepers_pk
DO UPDATE SET
    match_id = excluded.match_id,
    match_date = excluded.match_date,
    season = excluded.season,
    player_link = excluded.player_link,
    player = excluded.player,
    country_link = excluded.country_link,
    nationality = excluded.nationality,
    age = excluded.age,
    minutes = excluded.minutes,
    shots_on_target_against = excluded.shots_on_target_against,
    goals_against_gk = excluded.goals_against_gk,
    saves = excluded.saves,
    save_pct = excluded.save_pct,
    psxg_gk = excluded.psxg_gk,
    passes_completed_launched_gk = excluded.passes_completed_launched_gk,
    passes_launched_gk = excluded.passes_launched_gk,
    passes_pct_launched_gk = excluded.passes_pct_launched_gk,
    passes_gk = excluded.passes_gk,
    passes_throws_gk = excluded.passes_throws_gk,
    pct_passes_launched_gk = excluded.pct_passes_launched_gk,
    passes_length_avg_gk = excluded.passes_length_avg_gk,
    goal_kicks = excluded.goal_kicks,
    pct_goal_kicks_launched = excluded.pct_goal_kicks_launched,
    goal_kick_length_avg = excluded.goal_kick_length_avg,
    crosses_gk = excluded.crosses_gk,
    crosses_stopped_gk = excluded.crosses_stopped_gk,
    crosses_stopped_pct_gk = excluded.crosses_stopped_pct_gk,
    def_actions_outside_pen_area_gk = excluded.def_actions_outside_pen_area_gk,
    avg_distance_def_actions_gk = excluded.avg_distance_def_actions_gk;